{
 "title": "Subcoin",
 "tags": [
  "substrate",
  "subcoin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Unbounded channels",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "substrate_unbounded_channel_len",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Subcoin sync peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subcoin_p2p_connected_peers", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Subcoin network bandwidth",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subcoin_p2p_bandwidth", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Substrate sync peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Substrate network bandwidth",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Block execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "block_execution_time_milliseconds",
     "legendFormat": "{{block_height}}"
    }
   ]
  },
  {
   "title": "Addresses",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subcoin_p2p_addresses", "legendFormat": "{{status}}" }
   ]
  }
 ]
}