[package]
name = "subcoin-crypto"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
chacha20 = "0.9.1"
num-bigint = "0.4.6"
num-traits = "0.2.19"
sha2 = "0.10.8"

[dev-dependencies]
hex-literal = "0.4.1"
