[book]
title = "Subcoin Book"
authors = ["Liu-Cheng Xu"]
language = "en"
description = "A comprehensive guide to Subcoin, a Bitcoin Node in Substrate."
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
additional-css =["src/css/custom.css"]
git-repository-url = "https://github.com/subcoin-project/subcoin"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/subcoin-project/subcoin/edit/main/docs/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
